CREATE TABLE USER(
    ID INT  NOT NULL PRIMARY KEY AUTO_INCREMENT,
    ACCOUNT_ID VARCHAR(100),
    NAME VARCHAR(50),
    GMT_CREATE BIGINT,
    GMT_MODIFIED BIGINT,
    TOKEN CHAR(36),
    BIO VARCHAR(256)
)